### ISSUE TITLE
testで使用している変数名maxAを変える

### ISSUE THREAD

**Issue by kotatsugame** [universato/ac-library-rb#16]
#10 で議論していたものをissueにしました。何がいいでしょうか？現在の候補は

* max
* max_a

です。

**Comment by universato** [comment]
Issueありがとうございます!!
機能的に変数名を`max`として問題ないかもしれませんが、`Array#max`を想像させて少し違和感を感じるので、深い意味のない変数であることを強調して`m`ぐらいが良いかと思いました。

**Comment by 9sako6** [comment]
直接文字の範囲を書いてしまうのはどうでしょう。

```diff
- (rand(maxA) + ?\s.ord).chr
+ rand("\s".ord..'~'.ord).chr
```

? で文字リテラルになる記法は遠い将来なくならないとも限らないので、ライブラリの実装で積極的に使う必要はないかなと思いました。Ruby3 さみっとという場で、Matz が雑談的に話していた気がします。（危うきに近寄らずということで）
[Matz が地上げしたいモノリスト](https://hackmd.io/@ko1/ruby3samitto#Matz-%E3%81%8C%E5%9C%B0%E4%B8%8A%E3%81%92%E3%81%97%E3%81%9F%E3%81%84%E3%83%A2%E3%83%8E%E3%83%AA%E3%82%B9%E3%83%88)

maxA を整数の最大値として使っている部分は max_num, max_number などを考えました。すでに実装されているように、マジックナンバーを変数に格納しているのは良いとおもいます！

**Comment by kotatsugame** [comment]
randがrangeを引数に取れるのを知りませんでした……文字コードの範囲を書くのは、現在のごちゃごちゃやっているものより遥かに良い実装ですね！これは確実に採用したいです。

**Comment by kotatsugame** [comment]
ランダムに生成する文字列は、現在表示可能な文字、つまり空白からチルダまでのみを含むようにしています。わざわざ表示不可能な文字まで生成してテストする必要はないですよね？

**Comment by kotatsugame** [comment]
挙げられたものだと、変数名はmax_numにしたいです。

**Comment by 9sako6** [comment]
表示可能文字のテストで十分だと思います 🙆 🙆 🙆

**Comment by universato** [comment]
いいですね！

?リテラルは、直近のRuby Kaigi終わりのZoomでの感想戦で少し話題に上っていましたね。
以前より削除してくれという声があるものの、Matz氏は「emacs由来の文法で、削除したいけど、使っている人がいるから削除しにくい」ようなことを言っていました。他のRuby開発者のそらはさんは、使っているから残して欲しいと言ってました。
慣れない人が多いので自分は使わないですけど、1文字というのがわかりやすいので使いたい人がいれば尊重したいなと思ってましたが。
