### ISSUE TITLE
READMEに書きたいことを整理する

### ISSUE THREAD

**Issue by universato** [universato/ac-library-rb#29]
# 何を書きたいか整理する

## 書きたいと思っていること(概要)

- 使い方(How to Use) 
- ディレクトリ構造を示す(Directories)
- コントリビュート方法(How to Contribute)
- ライセンスを明示したい(LICENSE)
- ドキュメントの見方やリンクをつけたい(Documents and links for them)
- このリンクを追加したい → [AtCoder Library \(日本語訳\) \- けんちょんの競プロ精進記録](https://drken1215.hatenablog.com/entry/2020/09/08/181500)

## 考えていること、書きたいと思っていること(詳細)

- 使い方(How to Use)
  - 現状、「ディレクトリを漁って、コードをコピペして使って下さい」という形。
  - 「ドキュメントが未完成なので、本家ACLのドキュメントを参考にして下さい」の一言が欲しいかもしれないです。
- ドキュメントの見方やリンクをつけたい(Documents and links for them)
- ディレクトリ構造を示す(Directories)
  - 図は明示しなくても良さそう。
  - 本家ACLライブラリを真似している旨を書く。
  - `src`ディレクトリの中にコードがあることを書く。(本家ライブラリのディレクトリは`atcoder`で異なる)
- コントリビュート方法(How to Contribute)
  - お好きにという感じです。
- ライセンスを明示したい(LICENSE)
  - 現状、本家ライブラリのソースのライセンスを置いていて、権利も責任も放棄しているはず。
  - 「バグがあってもACできなくても責任とれないので、バグあったら報告・修正して下さい」という気分。

# 参考

他の言語のACLライブラリが参考にできそう
[Unofficial Portings of AtCoder Library (Googleスプレッドシート)](https://docs.google.com/spreadsheets/d/19jMAqUbv98grVkLV_Lt54x5B8ILoTcvBzG8EbSvf5gY/edit#gid=0)

**Comment by 9sako6** [comment]
本家ライブラリ移植の進捗具合もあると嬉しい気がしました。

**Comment by universato** [comment]
Issue開いてそこそこ経過したが、書きたいこと書いて飽きてきた感じがあるので、そろそろ閉じよう。
移植する必要のあるものは、基本的に終わったという認識。
ちょっとconvolutionの過去のものを復活させたいけど、これは別Issueに起票済み。
