### ISSUE TITLE
Add 2-SAT Document(Ja)

### ISSUE THREAD

**Issue by 9sako6** [universato/ac-library-rb#33]
まだどなたも取り組んでおられないようでしたら、やります。

**Comment by universato** [comment]
自分は、ModIntと自分がやったところあたりを優先的にやろうかと思っているので、大丈夫だと思います！(また、他の人がやりたければ、どうぞという感じです)
特にテンプレート決まっているわけでないので、ある程度自由に書いてもらえればと思います。一応、自分が作ったmdファイルは、本家ドキュメントをベースにしたつもりですが、それが良いのかはよくわかっていないです。

**Comment by 9sako6** [comment]
ありがとうございます！数式をどう書くかちょっと悩ましいですが、やってみますね。
> 一応、自分が作ったmdファイルは、本家ドキュメントをベースにしたつもりですが、それが良いのかはよくわかっていないです

すでにユニさんが追加されたドキュメントは読みやすいと思います。参考にして書いてみます。
