### ISSUE TITLE
Change directory name from `src` to `lib`

### ISSUE THREAD

**Issue by universato** [universato/ac-library-rb#49]
他言語を見て`src`ディレクトリにライブラリを入れてしまいましたが、改めて考えたところ`src`はコンパイル言語でのコンパイル前のコードを入れるイメージです。
`bundle gem`でgemの雛形を作るときに`lib`ディレクトリが作られるそうで、Ruby使う人にとっては`lib`がわかりやすいのかなと思いました。本レポジトリの性質的にも`lib`があっていると思いました。
なお、自分としては、本家AtCoderライブラリに合わせているものの、AtCoderに限らず一般的に競プロなどで使われるライブラリを置いているつもりなので、本家ライブラリに合わせてatcoderという名称を用いるのはわかりやすいですが美しくない気がするので反対です。

[ディレクトリ名srcとかの謎と作法 \- WebTecNote](https://tenderfeel.xsrv.jp/memo/1229/)
> srcディレクトリにソースを入れ、ビルド結果をbuildディレクトリに入れるのは「コンパイルする言語ではお馴染みの作法」でも、コンパイル不要だとそうでもない。
EclipseなんかでJavaの新規プロジェクト作るとデフォルトでsrcというフォルダが作られるがPythonやRubyでは作られない。

**Comment by surpace** [comment]
私としましては、 `lib/atcoder` にするのがいいのではないかと思います。
必要以上にややこしいかもしれませんが、 [expander-rb](https://github.com/surpace/expander-rb) でバンドルするときに `require "atcoder/max_flow"` のような書き方ができるようになるので。
いえ別に `require "max_flow"` でもいいですし、 expander-rb の方を書き換えてもいいのですが。

**Comment by universato** [comment]
コメントありがとうございます！

PriorityQueueはこっちにはあったりAtCoderライブラリにはなかったり、AtCoder以外の競プロサイトなどで使える観点で、もしそういう方向性なら`atcoder`じゃなくて`aclibrary`などの名称にしたいです。

ただ、今のところメインがコピペ想定で`require`を使わないので、まだ階層は深くはしたくないです。

他に、gem化したいという少し気持ちがあり、そういうときは`require "aclibrary"`などで書けると嬉しそうです。
