### ISSUE TITLE
dsuのgroups_with_leaderでgroup_byを使ってはどうか

### ISSUE THREAD

**Issue by kotatsugame** [universato/ac-library-rb#66]
やってることは全く同じなので、専用のメソッドがあるならそれを使うべきだと思いますが、どうですか

**Comment by universato** [comment]
とてもいいですね😄
`h = Hash.new { |hash, key| hash[key] = [] }` ← 今のこういう部分は独特でわかりにくいですし、コードがスッキリするので、とても良い思います。ただ、万が一、とても遅くなるようなことがあれば保留やリジェクトという形になると思います。

話が少し逸れますが、Hashの一般的な命名の1つが`value_by_key`らしいので、`groups_with_leader`を`groups_by_leader`と短くしたいと思ってます。このメソッド自体、本家ライブラリになく「あったら便利なこともあるかもしれない」でなんとなく切り出したもので、`groups`メソッドに取り込んでもいいかな等と思ったりしますが(取り込んだ方が速い?)。
【参考】
[Map型の変数の命名について考えた \- yn2011's blog](http://pokuwagata.hatenablog.com/entry/2019/04/03/002217)
[私的アンリーダブルコード―他人を発狂させるための 9 のテクニック \- あらびき日記](https://abicky.net/2017/01/22/071157/#section-1)

**Comment by kotatsugame** [comment]
dsuのグループのリーダーに「たまたま根になっている」以外特別な意味はない・持たせてはいけないと思っているので、groups_with_leaderもいらないかなと思います。group_byを使うならコードもかなりすっきりしますし。

**Comment by universato** [comment]
> 特別な意味はない・持たせてはいけない

ですよね。強い言葉で言ってもらえて、ありがたいです。
YAGNIの原則にもならって(さっき覚えた言葉)、`groups_with_leader`の削除に1票です!!
