### ISSUE TITLE
リンク先ブランチが main ではなく master のままになっている

### ISSUE THREAD

**Issue by ysjj** [universato/ac-library-rb#86]
リダイレクトされるので現状実害はないのですが、[README.md](/universato/ac-library-rb/blob/main/README.md) および [document_ja/index.md](/universato/ac-library-rb/blob/main/document_ja/index.md) のリンクに含まれるブランチ名が main ではなく master のままなのでクリック後、以下の様なメッセージが表示されます。
![image](https://user-images.githubusercontent.com/306369/226623205-1c02e2fc-1b6f-4463-a231-00b8aa764244.png)

**Comment by universato** [comment]
Thank you! 
ありがとうございます! 修正しました > https://github.com/universato/ac-library-rb/commit/98867489916f3dbb96db99661fbd67440e1916a8
